name: kafka-test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: gradle:6.9.2-jdk11
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Docker Network
        run: docker network create kafka-network || true
      
      - name: Start Kafka with Docker Compose
        run: |
          cat <<EOF > docker-compose.yml
          version: '3.8'
          services:
            zookeeper:
              image: wurstmeister/zookeeper:latest
              container_name: zookeeper
              networks:
                - kafka-network
              ports:
                - "2181:2181"

            kafka:
              image: wurstmeister/kafka:latest
              container_name: kafka
              networks:
                - kafka-network
              ports:
                - "9092:9092"
              environment:
                KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
                KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
                KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
                KAFKA_BROKER_ID: 1
              depends_on:
                - zookeeper
          
          networks:
            kafka-network:
              external: true
          EOF
          docker-compose up -d
      
      - name: Connect Container to Kafka Network
        run: docker network connect kafka-network \$(hostname)

      - name: Wait for Kafka to be Ready
        run: |
          echo "Waiting for Kafka to be ready..."
          for i in {1..30}; do
            if docker exec kafka kafka-topics.sh --bootstrap-server kafka:9092 --list > /dev/null 2>&1; then
              echo "Kafka is ready!";
              exit 0;
            fi
            echo "Attempt $i: Kafka not ready yet...";
            sleep 10;
          done
          echo "Kafka failed to start in time";
          docker logs kafka
          exit 1;

      - name: Ensure Gradle Wrapper is Executable
        run: chmod +x ./gradlew

      - name: Run Kafka Tests
        run: ./gradlew test --info
        env:
          KAFKA_BROKER: kafka:9092

      - name: Cleanup
        if: always()
        run: docker-compose down
