name: kafka-test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    container: gradle:6.9.2-jdk11
    services:
      zookeeper:
        image: wurstmeister/zookeeper:latest
        ports: [2181:2181]
      kafka:
        image: wurstmeister/kafka:latest
        ports: [9092:9092]
        env:
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x ./gradlew
      - run: ./gradlew test
        env:
          KAFKA_BROKER: kafka:9092
